# -*- coding: utf-8 -*-
"""AIMLSession7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hIhyFF1f4llpudXq3J03OSVdy-lOAIH7
"""

#importing libraries
import pandas as pd

df = pd.read_csv('iris.data',names=['sl','sw','pl','pw','species'])

df.head()  #will display top 5 samples

#feature columns sl,sw,pl,pw  target column species

df.head(10)

df.tail()

df.tail(10)

df.shape

no_of_rows = df.shape[0]
print(no_of_rows)

no_of_cols = df.shape[1]
print(no_of_rows)
no_of_cols

df.ndim

df.dtypes

def example_data_conversion(file):
  df1 = pd.read_csv('iris.data',names=['sl','sw','pl','pw','species'])
  return df1

a =example_data_conversion('iris.data')

a.head()

type(a)

#Method 1 dataframe.column name
df.sl[0:6] #if seperated by space,mulitple columns (problem with this notation)

#Method 2 datframe['column name']
df[['sl','pl']]

df.iloc[0:6,0]  #iloc[rows,columns]

df.iloc[0:6,:]  #iloc[rows,columns]

df.isna().sum()  #to check if there are any null values

df['pl'].rename('pl_new',inplace=True)

df.rename(columns={'sl':'sepal_length'},inplace=True)

df.head()

df.drop('sl_new',axis=1,inplace=True) #axis=1 for column

df.head()

import matplotlib.pyplot as plt
import seaborn as sns

sns.pairplot(df,hue='species')
plt.show()

df.species.unique()

df.species.nunique()

df.species.value_counts()

