# -*- coding: utf-8 -*-
"""Python_Basics_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fKl6C2C1FZuW1-MqMcrR4CNTYhDKY7zm
"""

class Employee:
  def __init__(self,id):
    '''this is an Example Function in python'''
    self.id=id

  def add_two(self,a,b):
   return a+b

Employee

employee1 = Employee(1002)
employee1

employee1.id

employee1.add_two(3,4)

e2 = Employee(2)

e2.add_two(6,7)

class Person:
  def add(self,id):
    return id ** 2

p1 = Person()
p1.add(3)

class Employee:
  def __init__(self,id):
    print('inside __init__()')
    print(f'self = {self}')
    self.id = id

E1 = Employee(1002)
print(f'E1 = {E1}')

E1.id

class Employee:
  def __init__(self,id,first_name,last_name):
    self.id = id
    self.first_name = first_name
    self.last_name = last_name
  def get_id(self):
    return self.id
  def get_full_name(self):
    return f'{self.first_name} {self.last_name}'

E1 = Employee(1002,'John','Doe')
E1

E1.id

E1.first_name

E1.last_name

E1.get_id()

E1.get_full_name()

#inheritance
class Developer(Employee):   #subclass
  def __init__(self,id,first_name,last_name,salary):
    super().__init__(id,first_name,last_name)
    self.salary = salary

help(Developer)

d1 = Developer(1003,'peter','deo',100000)

d1.get_full_name()

d1.salary

class Myclass:
  ''' this i class level doc string '''
  def __init__(self,a,b):
    ''' this is a init dunder function'''
    self.a = a
    self.b = b
  def __habeeb__(self):
    '''This is user defined dunder function'''
    return f'{self.a} {self.b}'

m1 = Myclass('peter',20)
m1

print(m1)

class Myclass:
  def __init__(self,name,age):
    self.name = name
    self.age = age
  def __add__(self,other):
    '''hello'''
    result = self.age + other.age
    return Myclass(f'{self.name} and {other.name}',result)

m1 = Myclass('object1',56)

m2 = Myclass('object2',25)

combined = m1 + m2

print(combined.name)
print(combined.age )

Myclass.__add__.__doc__

from teestclass import Employee

e1 = Employee('peter',25,4545454)

e1.name

e1.add_two(3,4)

from teestclass import Employee