# -*- coding: utf-8 -*-
"""PythonBasics_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h53f3VL7vPe2kro_MH7PFa6TrplFiYZH

## **Learn Scalar and vector concepts in Python**
"""

import numpy as np

a_scalar = np.array(20)

print(a_scalar)  #a = 10

a_scalar.ndim

a_scalar.shape

a_scalar.size

a_vector = np.array([1,2,3,45])

a_vector.ndim

a_vector.shape

a_vector.size

print(a_vector)

a_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a_matrix)

a_matrix.ndim

a_matrix.shape

a_matrix.size

a_matrix1 = np.arange(1, 16).reshape(3, 5)
print(a_matrix1)

a_matrix1[1:3,1:3]

a_matrix1[1:3,2:4]

a_matrix1[2,3:]

a_tensor = np.arange(1,37).reshape((3,3,4))
print(a_tensor)

a_tensor[1,1:3,1:3]

a_tensor[2,1,:]

a_tensor[2,1,0:4]

a_tensor[2,1,0:]

import imageio as io  #to read the image in pixels

data = np.zeros((200,200,3),dtype=np.uint8)

print(data)

import matplotlib.pyplot as plt  #to display the data

data[:,:,0] = 125 #red
data[:,:,1] = 20  #green
data[:,:,2] = 123  #blue
io.imsave('test.png',data)
t = io.v3.imread('test.png')
plt.imshow(t)
plt.show()

