# -*- coding: utf-8 -*-
"""Python_Basics-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dg3iHUE7wn7jAoSBXwCJE2on1mo003Ym

Python Functions
"""

def add_two(a,b): #user defined function
  return a + b

add_two(2,3)

def multi_table(a): #user defined function
  for i in range(1,11):
    print(f'{a} x {i} = {a*i}')

n = int(input('Enter a number: ')) #user input
multi_table(n)

#function with default value
def add_two_default(a = 2,b = 3): #user defined function
  print(a+b)

add_two_default(5,5)

print('hello')  #in_built function

#anonymous functions

a = lambda a : a ** 2 #lambda function

a(4)

(lambda a : a ** 2)(3)

(lambda : 'hello')() #anonymous function

a = lambda : 'hello' #anonymous function

a()

from math import pi #importing a module

pi

def square(r): #user defined function
  return r ** 2

def area_of_circle(pi,r,f): #user defined function
  return pi * f(r)

area_of_circle(pi,2,square) #calling a function

#map filter

l = [1,2,3,4,5]

list(map(square,l)) #map

def even_check(n):
  if n%2==0:
    return n

even_check(5) #user defined function

list(map(even_check,l)) #filter

list(filter(even_check,l)) #filter

list(filter(lambda n : n%2 == 0,l)) #filter

from testfunc import add_three  #modularity (Upload a testfunc.py if working with colab before you run this command)

add_three(3,4,5) #importing a function from a module

def vowelcount(s): #user defined function
  count = 0
  vowels = 'aeiouAEIOU'
  for i in s:
    if i in vowels:
      count += 1
  return count

vowelcount('nasreen')  #calling a function

s = 'shalmali'  #string
for i in s:
  if i in 'nasreen':
    print(i)