# -*- coding: utf-8 -*-
"""Python_Basics_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fIDlns_qMIAD0NAWXn2vCs4SuX7R_M3r
"""

#Welcome to the Python Basics Course

!python --version # Always check n note the Python version

print("hello") # Simple print

"""Basic data types in Python"""

a = 10 # variable declaration

type(a) # To check the type of the variable a

b = 89.7 # variable declaration

type(b)

c = True # variable declaration

type(c)

d = "Shalmali"

type(d)

"""Operators in Python"""

a = 3
b =2

#addition
print(a + b)

#Multiplication
print(a * b)

#substraction
print(a - b)



