# -*- coding: utf-8 -*-
"""AIMLSession8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vhMFRU7m716uZ4mHYow2J5VoLl9XBZzg
"""

import pandas as pd

df = pd.read_csv('auto-mpg.data',delimiter='\s+',names=['mpg','cylinders','displacement','horsepower','weight','acceleration','model_year','origin','car_name'])

df.head()

df.isna().sum()

df.dtypes

df['horsepower'] = df['horsepower'].astype('float')

#Query Data Frame
df[df['horsepower'] == '?']

df.shape

df1 = df[df['horsepower'] != '?']

df1.shape

df1.dtypes

df1['horsepower'] = df1['horsepower'].astype('float')

df1.dtypes

def example(a):
  return 2 * a

df['cylinders'] = df['cylinders'].apply(example)

df.head()

names = ['mpg','cylinders','displacement','horsepower','weight','acceleration','model_year','origin','car_name']

df = pd.read_csv('auto-mpg.data',delim_whitespace=True,names=names,na_values='?')

df.head()

df.isna().sum()

df.shape

df.dtypes

df = df.dropna()

df.shape

mean_hp = df['horsepower'].mean()
mean_hp

df['horsepower'].fillna(mean_hp,inplace=True)

df.shape

df[df['horsepower'] == 104.46938775510205]

for i in df['horsepower']:
  print(i)

df.dtypes

for i in df['horsepower']:
  if isinstance(i,str):
    print(f'found {i}')

